server:
  port: 8888
  
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test-service
#          uri: http://localhost:8100
#          predicates:
#            - Path=/**

logging:
  level:
    root: INFO
    org.springframework.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.loadbalancer: INFO


management:
  endpoints:
    web:
      exposure:
        include: '*'

